/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 04-nov-2012, 14:20:41
 */
package proyectodanielllanos;

import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Master
 */
public class Main extends javax.swing.JFrame {

    private ArrayList<Referencia> referencias = new ArrayList<Referencia>();
    private ArrayList<Vehiculo> vehiculos = new ArrayList<Vehiculo>();
    boolean afiliado;

    /** Creates new form Main */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        nroAfiliacion.setEnabled(false);
        soat.setEnabled(false);
        regRevision.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreRef = new javax.swing.JTextField();
        nroPuertas = new javax.swing.JTextField();
        cilindraje = new javax.swing.JTextField();
        velMax = new javax.swing.JTextField();
        RRef = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        selRef = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        propNombre = new javax.swing.JTextField();
        propId = new javax.swing.JTextField();
        PropTel = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nroAfiliacion = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        aseguradora = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        soat = new javax.swing.JTextField();
        afi = new javax.swing.JRadioButton();
        oca = new javax.swing.JRadioButton();
        regVehiculo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        busPlaca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        estado = new javax.swing.JComboBox();
        regRevision = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        nroRevision = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        informes = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Numero de puertas:");

        jLabel3.setText("Cilindraje:");

        jLabel4.setText("Vel. Maxima:");

        nroPuertas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nroPuertasKeyTyped(evt);
            }
        });

        cilindraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cilindrajeKeyTyped(evt);
            }
        });

        velMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                velMaxKeyTyped(evt);
            }
        });

        RRef.setText("Registrar");
        RRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(velMax))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cilindraje))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nroPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nombreRef)))
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RRef)
                        .addGap(225, 225, 225))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nroPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(velMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(RRef)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Referencia", jPanel1);

        selRef.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Referencia:");

        jLabel6.setText("Placa");

        jLabel7.setText("Modelo");

        jLabel8.setText("Nombre Propietario");

        jLabel9.setText("Cedula Propietario");

        jLabel10.setText("Telefono Propietario");

        modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modeloKeyTyped(evt);
            }
        });

        propId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                propIdKeyTyped(evt);
            }
        });

        PropTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PropTelKeyTyped(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Afiliado"));

        jLabel11.setText("Numero de Afiliacion");

        nroAfiliacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nroAfiliacionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(nroAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nroAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ocasional"));

        jLabel12.setText("Aseguradora");

        aseguradora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Mafre", "Sura", "Otra" }));

        jLabel13.setText("Numero de SOAT");

        soat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soatKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(aseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(soat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        afi.setText("Afiliado");
        afi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afiActionPerformed(evt);
            }
        });

        oca.setText("Ocasional");
        oca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocaActionPerformed(evt);
            }
        });

        regVehiculo.setText("Registrar Vehiculo");
        regVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(placa)
                                    .addComponent(selRef, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(propId)
                                    .addComponent(PropTel)
                                    .addComponent(propNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(modelo)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(regVehiculo)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(afi)
                                .addGap(18, 18, 18)
                                .addComponent(oca))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel8))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afi)
                    .addComponent(oca))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(selRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(propNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(propId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(PropTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(regVehiculo)
                        .addGap(42, 42, 42))))
        );

        jTabbedPane1.addTab("Registrar Vehiculo", jPanel2);

        jButton1.setText("Buscar placa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Fecha");

        jLabel15.setText("Descripcion");

        jLabel16.setText("Estado");

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Cumplido", "No cumplido", "Pendiente" }));

        regRevision.setText("Registrar Revision");
        regRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRevisionActionPerformed(evt);
            }
        });

        jLabel17.setText("Revisiones hechas:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(busPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nroRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(regRevision)
                .addGap(59, 59, 59))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(nroRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(regRevision)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Revisiones", jPanel3);

        informes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Total a pagar por revisiones", "Revisiones en un estado --", "Pagos de revisiones de vehiculo afiliado", "Verificar si es vehiculo afiliado de bajo riesgo", "Pagos de revisiones de vehiculo ocasional", "Reporte minimo vehiculo ocasional", "Vehiculos de una gama determinada", "Listado de vehiculos de bajo riesgo", "Listado con reportes minimos", "Total a pagar por revisiones" }));
        informes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informesActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel18.setText("INFORMES");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(informes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(informes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informes", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void RRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRefActionPerformed
    if (validarCamposLlenosReferencia()) {
        Referencia r = new Referencia(nombreRef.getText(), Integer.parseInt(nroPuertas.getText()), Double.parseDouble(cilindraje.getText()), Double.parseDouble(velMax.getText()));
        r.Gama();
        referencias.add(r);

        //selRef.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        String[] selref = new String[referencias.size()];
        for (int i = 0; i < referencias.size(); i++) {
            selref[i] = referencias.get(i).getNombre();
        }
        selRef.setModel(new javax.swing.DefaultComboBoxModel(selref));
        limpiarPanelRef();
        JOptionPane.showMessageDialog(this, "Registro Exitoso");
    }
}//GEN-LAST:event_RRefActionPerformed

private void nroPuertasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroPuertasKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }
}//GEN-LAST:event_nroPuertasKeyTyped

private void cilindrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrajeKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }
}//GEN-LAST:event_cilindrajeKeyTyped

private void velMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_velMaxKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }
}//GEN-LAST:event_velMaxKeyTyped

private void propIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_propIdKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }
}//GEN-LAST:event_propIdKeyTyped

private void PropTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropTelKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }
}//GEN-LAST:event_PropTelKeyTyped

private void nroAfiliacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroAfiliacionKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }

}//GEN-LAST:event_nroAfiliacionKeyTyped

private void soatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soatKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }
}//GEN-LAST:event_soatKeyTyped

private void afiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afiActionPerformed
    if (afiliado) {
        afiliado = false;
        afi.setSelected(false);
        oca.setSelected(true);
        aseguradora.setEnabled(true);
        soat.setEnabled(true);
        nroAfiliacion.setEnabled(false);
    } else {
        afiliado = true;
        afi.setSelected(true);
        oca.setSelected(false);
        aseguradora.setEnabled(false);
        soat.setEnabled(false);
        nroAfiliacion.setEnabled(true);
    }
}//GEN-LAST:event_afiActionPerformed

private void ocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocaActionPerformed
    if (afiliado) {
        afiliado = false;
        afi.setSelected(false);
        oca.setSelected(true);
        aseguradora.setEnabled(true);
        soat.setEnabled(true);
        nroAfiliacion.setEnabled(false);
    } else {
        afiliado = true;
        afi.setSelected(true);
        oca.setSelected(false);
        aseguradora.setEnabled(false);
        soat.setEnabled(false);
        nroAfiliacion.setEnabled(true);
    }
}//GEN-LAST:event_ocaActionPerformed

private void regVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regVehiculoActionPerformed
    if (validarCamposLlenosVehiculo()) {
        Propietario p = new Propietario(propNombre.getText(), Integer.parseInt(propId.getText()), Integer.parseInt(PropTel.getText()));
        Referencia r = null;
        for (int i = 0; i < referencias.size(); i++) {
            if ((selRef.getSelectedItem() + "").equals(referencias.get(i).getNombre())) {
                r = referencias.get(i);
            }
        }
        if (afiliado) {
            if (nroAfiliacion.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Digite el numero de afiliacion");
            } else {
                Afiliado a = new Afiliado(Integer.parseInt(nroAfiliacion.getText()), Integer.parseInt(modelo.getText()), placa.getText(), p, r, new ArrayList<Revision>());
                vehiculos.add(a);
                JOptionPane.showMessageDialog(propNombre, "Registro Exitoso");
            }
        } else {
            if (soat.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Digite el numero de SOAT");
            } else {
                Ocasional o = new Ocasional(aseguradora.getSelectedItem() + "", Integer.parseInt(soat.getText()), Integer.parseInt(modelo.getText()), placa.getText(), p, r, new ArrayList<Revision>());
                vehiculos.add(o);
                JOptionPane.showMessageDialog(propNombre, "Registro Exitoso");
            }
        }

        limpiarPanelRegVehiculo();

    }
}//GEN-LAST:event_regVehiculoActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (buscarVehiculo(busPlaca.getText())) {

        if (Integer.parseInt(nroRevision.getText()) == 3) {
            JOptionPane.showMessageDialog(this, "El vehiculo ya tiene tres revisiones, no se pueden crear mas");
            placa.setText("");
        } else {
            crearFecha();
            busPlaca.setEditable(false);
            regRevision.setEnabled(true);
        }
    } else {
        JOptionPane.showMessageDialog(this, "La placa digitada no se encuentra registrada");
    }


}//GEN-LAST:event_jButton1ActionPerformed

private void modeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloKeyTyped
    int c = evt.getKeyChar();
    if (!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }    // TODO add your handling code here:
}//GEN-LAST:event_modeloKeyTyped

private void regRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRevisionActionPerformed
    if (validarCamposLlenosRegRevisiones()) {
        Revision r = new Revision(fecha.getText(), descripcion.getText(), estado.getSelectedItem() + "");
        agregarRevision(busPlaca.getText(), r);
        busPlaca.setEditable(true);
        JOptionPane.showMessageDialog(this, "Registro Exitoso");
        regRevision.setEnabled(false);
        limpiarPanelRevision();
    }
}//GEN-LAST:event_regRevisionActionPerformed

private void informesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informesActionPerformed
    area.setText("");
    if ((informes.getSelectedItem() + "").equals("Total a pagar por revisiones")) {
        double costotalRevisiones = 0;
        for (int i = 0; i < vehiculos.size(); i++) {
            for (int j = 0; j < vehiculos.get(i).getRevisiones().size(); j++) {
                costotalRevisiones += vehiculos.get(i).getRevisiones().get(j).getCosto();

            }

        }
        area.setText("El monto total recaudado por revisiones es: " + costotalRevisiones);
    } else {
        switch (informes.getSelectedIndex()) {
            case 1:
                Vehiculo v = retornarVehiculo(JOptionPane.showInputDialog("Digite la placa del vehiculo"));
                if (v != null) {
                    area.setText(v.calcularCostoRevisiones());
                }
                break;
            case 2:
                v = retornarVehiculo(JOptionPane.showInputDialog("Digite la placa del vehiculo"));
                if (v != null) {
                    area.setText(v.revisionesEnEstado());
                }
                break;
            case 3:
                v = retornarVehiculo(JOptionPane.showInputDialog("Digite la placa del vehiculo"));
                if (v != null) {
                    if (v instanceof Afiliado) {
                        Afiliado a = (Afiliado) v;
                        area.setText((a.calcularCostoRevisiones()));
                    } else {
                        JOptionPane.showMessageDialog(this, "La placa digitada no corresponde a un vehiculo Afiliado");
                    }

                }
                break;
            case 4:
                v = retornarVehiculo(JOptionPane.showInputDialog("Digite la placa del vehiculo"));
                if (v != null) {
                    if (v instanceof Afiliado) {
                        Afiliado a = (Afiliado) v;
                        area.setText((a.revisionesBajoRiesgo()));
                    } else {
                        JOptionPane.showMessageDialog(this, "La placa digitada no corresponde a un vehiculo Afiliado");
                    }

                }
                break;
            case 5:
                v = retornarVehiculo(JOptionPane.showInputDialog("Digite la placa del vehiculo"));
                if (v != null) {
                    if (v instanceof Ocasional) {
                        Ocasional a = (Ocasional) v;
                        area.setText((a.calcularCostoRevisiones()));
                    } else {
                        JOptionPane.showMessageDialog(this, "La placa digitada no corresponde a un vehiculo Ocasional");
                    }

                }
                break;
            case 6:
                v = retornarVehiculo(JOptionPane.showInputDialog("Digite la placa del vehiculo"));
                if (v != null) {
                    if (v instanceof Ocasional) {
                        Ocasional a = (Ocasional) v;
                        area.setText((a.reporteMinimo()));
                    } else {
                        JOptionPane.showMessageDialog(this, "La placa digitada no corresponde a un vehiculo Ocasional");
                    }

                }
                break;
            case 7:
                Object[] o = {"Gama Baja", "Gama Media", "Gama Alta"};
                String opcion = JOptionPane.showInputDialog(this, "Seleccione la gama por la que desea buscar ", "Seleccione la Gama", 0, null, o, o[0]) + "";
                area.setText(buscarPorGama(opcion));
                break;
            case 8:
                boolean c=false;
                String msj = "";
                for (int i = 0; i < vehiculos.size(); i++) {
                    if (vehiculos.get(i) instanceof Afiliado) {
                        Afiliado a = (Afiliado) vehiculos.get(i);
                        if (a.esBajoRiesgo()) {
                            msj += a.listado() + "\n";
                            c=true;
                        }
                    }
                }
                if(c)
                area.setText(msj);
                else
                    area.setText("No se encontraron vehiculos bajo riesgo");
                break;
            case 9:
                 c=false;
                msj = "";
                for (int i = 0; i < vehiculos.size(); i++) {
                    if (vehiculos.get(i) instanceof Ocasional) {
                        Ocasional a = (Ocasional) vehiculos.get(i);
                        msj += a.reporteMinimo() + "\n";
                        c=true;
                    }
                }
                if(c)
                area.setText(msj);
                else
                    area.setText("No es encontraron vehiculos ocasionales con reportes minimos");
                break;
            case 10:
                double costotalRevisiones = 0;
                for (int i = 0; i < vehiculos.size(); i++) {
                    for (int j = 0; j < vehiculos.get(i).getRevisiones().size(); j++) {
                        costotalRevisiones += vehiculos.get(i).getRevisiones().get(j).getCosto();

                    }

                }
                area.setText("El monto total recaudado por revisiones es: " + costotalRevisiones);
                break;
        }
    }
}//GEN-LAST:event_informesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PropTel;
    private javax.swing.JButton RRef;
    private javax.swing.JRadioButton afi;
    private javax.swing.JTextArea area;
    private javax.swing.JComboBox aseguradora;
    private javax.swing.JTextField busPlaca;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField cilindraje;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JComboBox estado;
    private javax.swing.JTextField fecha;
    private javax.swing.JComboBox informes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nombreRef;
    private javax.swing.JTextField nroAfiliacion;
    private javax.swing.JTextField nroPuertas;
    private javax.swing.JLabel nroRevision;
    private javax.swing.JRadioButton oca;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField propId;
    private javax.swing.JTextField propNombre;
    private javax.swing.JButton regRevision;
    private javax.swing.JButton regVehiculo;
    private javax.swing.JComboBox selRef;
    private javax.swing.JTextField soat;
    private javax.swing.JTextField velMax;
    // End of variables declaration//GEN-END:variables

    private void limpiarPanelRef() {
        nombreRef.setText("");
        nroPuertas.setText("");
        cilindraje.setText("");
        velMax.setText("");
    }

    private boolean buscarVehiculo(String placa) {
        System.out.println("entroooooooooooooooooooooo");
        for (int i = 0; i < vehiculos.size(); i++) {
            System.out.println("entro2");
            System.out.println("la placa q llega" + placa + "La q busco" + vehiculos.get(i).getPlaca());
            if (placa.equals(vehiculos.get(i).getPlaca())) {
                System.out.println("entro3");
                nroRevision.setText(vehiculos.get(i).getRevisiones().size() + "");
                System.out.println("tamano: " + vehiculos.get(i).getRevisiones().size() + "");
                return true;
            }


        }
        return false;
    }

    private void crearFecha() {
        Date now = new Date();
        fecha.setText(DateFormat.getInstance().format(now));
        fecha.setEditable(false);
    }

    private void limpiarPanelRegVehiculo() {
        placa.setText("");
        modelo.setText("");
        propId.setText("");
        PropTel.setText("");
        propNombre.setText("");
        nroAfiliacion.setText("");
        soat.setText("");
        afi.setSelected(false);
        oca.setSelected(false);
    }

    private void agregarRevision(String placa, Revision r) {
        for (int i = 0; i < vehiculos.size(); i++) {
            if (placa.equals(vehiculos.get(i).getPlaca())) {
                vehiculos.get(i).agregarRevision(r);
            }
        }

    }

    private boolean validarCamposLlenosReferencia() {
        if (nombreRef.getText().equalsIgnoreCase("") || nroPuertas.getText().equalsIgnoreCase("") || cilindraje.getText().equalsIgnoreCase("") || velMax.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos");
            return false;
        } else {
            return true;
        }
    }

    private boolean validarCamposLlenosVehiculo() {
        if (placa.getText().equalsIgnoreCase("") || modelo.getText().equalsIgnoreCase("") || propId.getText().equalsIgnoreCase("") || PropTel.getText().equalsIgnoreCase("") || propNombre.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos");
            return false;
        } else {
            return true;
        }
    }

    private boolean validarCamposLlenosRegRevisiones() {
        if (busPlaca.getText().equalsIgnoreCase("") || fecha.getText().equalsIgnoreCase("") || descripcion.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos");
            return false;
        } else {
            return true;
        }
    }

    private Vehiculo retornarVehiculo(String placa) {
        for (int i = 0; i < vehiculos.size(); i++) {
            if (placa.equals(vehiculos.get(i).getPlaca())) {
                return vehiculos.get(i);
            }

        }
        JOptionPane.showMessageDialog(this, "El vehiculo con esa placa no existe");
        return null;
    }

    private String buscarPorGama(String gama) {
        String msj = "";
        for (int i = 0; i < vehiculos.size(); i++) {
            if (gama.equalsIgnoreCase(vehiculos.get(i).getReferencia().getGama())) {
                if (vehiculos.get(i) instanceof Afiliado) {
                    Afiliado a = (Afiliado) vehiculos.get(i);
                    msj += a.getInfo() + "\n";
                    ;
                } else {
                    Ocasional o = (Ocasional) vehiculos.get(i);
                    msj += o.getInfo() + "\n";
                    ;
                }
            }
            if (msj.length() == 0) {
                msj = "No hay vehiculos registrados con esa gama";
            }
        }
        return msj;
    }

    private void limpiarPanelRevision() {
        placa.setText("");
        fecha.setText("");
        descripcion.setText("");
        nroRevision.setText("");
    }
}
